# Generated by Django 5.1.7 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clonedvoice',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
